### ISSUE TITLE
Compose custom CSS properties 

### ISSUE THREAD

**Issue by braposo** [hauptrolle/stitches-utils#1]
Hey @hauptrolle thanks for this library, this is really useful! 

What do you think of adding a `compose` function (or something with a better name 😅) to create new utils based on specific CSS properties?

Was thinking something like:

```ts
function compose(...properties: (keyof CSSStyleDeclaration)[]) {
    return (config: never) => (value: string) => properties.reduce((final, cssProp) => {
        return {
            ...final,
            [cssProp]: value
        }
    }, {});
}
```

which would then be used like:

```js
export const { styled, css } = createStyled({
  utils: {
    size: compose('width','height'),
  },
});
```

Do you think this would make sense to include in this library?

If so, would you prefer to use an array as args or just spread the args like [this example](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABBOBbADnAzgUwBQB0R6ATnOjibDlgFyJ4DWOAnnMIgMIDKvULAGxwARHBAEBDEhNgIAlAG0AunMQBvAFCJtiEjiggSSPADcJAkDnpYoJGGADmqgLwA+RKXKVqWAnoAmIBD4eMD25gA0yFhYAApk6C7umjqpuvqGSClpOUQEYWCRWjlpChAx8eRK9GYWOMU5AL4NiI1Rao1yANwazRooYDaIWDAAXjiIzshomLh4AEQA7jD+UAAW81HzazgwDmtQ83Ia-QhYcEIEAnAOeCPjCwDM6AAeR8dAA)?

**Comment by braposo** [comment]
I'm happy to create a PR with this code by the way! Just wanted to check
with you first before creating it 😁

**Comment by hauptrolle** [comment]
Hi @braposo 👋,

thank you for your positive feedback. It is very appreciated! 😊

I think a `compose` function would be a nice addition to this library.  We could also use this function internally to avoid some boilerplate code. Regarding the name I am fine with `compose` or something like `composeUtil` to make it a little bit more specific.

I would prefer to just spread all arguments instead of an array. It's a little bit easier to write.

One thing I am not so sure about, is how we can type that function better, so that we can get autocomplete suggestions based on the theme values. But I guess this is another issue to solve.

Feel free to open a PR. 👍

**Comment by hauptrolle** [comment]
@braposo It is merged and a new version is published  👍 Good work!
